### PR TITLE
adapt to upstream changes, make tests and CI pass again

### LINKED ISSUE #30: CI fails
```
error: failed to load source for a dependency on `ethabi`
Caused by:
  Unable to update https://github.com/tomusdrw/ethabi.git#6082addb
```

https://travis-ci.org/paritytech/sol-rs/builds/356872202

can't reproduce locally

any ideas?

### PR DESCRIPTION
**Pull request by snd**
resolve #30 among other changes

### CODE REVIEW

File: example/src/main.rs [hunk 1]
```diff
@@ -7,23 +7,22 @@ extern crate ethereum_types as types;
 extern crate rustc_hex;
 extern crate solaris;
 
-
 fn main() {
-    solaris::main(include_bytes!("../res/BadgeReg_sol_BadgeReg.abi"));
```
Comment (tomusdrw) [inline example/src/main.rs]: Why is it reformatted? I think we should stick to 4 spaces and rustfmt for this repo. Will add an `.editorconfig`

Comment (snd) [reply example/src/main.rs]: i forgot that this repo uses spaces since the rest of parity uses tabs. will undo the reformatting

**Comment by snd** [comment]
will continue this once the following 2 PRs are merged:

https://github.com/paritytech/ethabi/pull/85

https://github.com/paritytech/parity/pull/8258

**Comment by snd** [comment]
@tomusdrw yes! i'll try to look at it later today

**Comment by snd** [comment]
@tomusdrw are you fine with changing the no longer working occurrences like `contract.function(input1, input2).transact(&evm)` to `evm.transact(contract.function(input1, input2)`?

this is easier to implement. it also makes more sense in my opinion to pass the encoded inputs to the evm instead of passing the evm to the encoded inputs.

**Comment by tomusdrw** [comment]
@snd Fine with me, let's see how the API looks like, we can always add an extension trait and blanket impl that trait for every `T: ContractFunction`.

My gut feeling is that `.call()` is a tiny bit better cause it's easier to chain it (with `.and_then/wait/`, etc). But I don't see any reasons why we couldn't support both ways initially to see which one is more ergonomic long-term.

**Comment by snd** [comment]
@tomusdrw 

> we can always add an extension trait and blanket impl that trait for every T: ContractFunction

that would simply call `evm.call/transact` - very easy to add.

> But I don't see any reasons why we couldn't support both ways initially to see which one is more ergonomic long-term.

👍

**Comment by snd** [comment]
travis fails at: https://travis-ci.org/paritytech/sol-rs/jobs/386427116#L994

```
error[E0308]: mismatched types
  --> tests/tests/test.rs:35:27
   |
35 |       let output: Address = evm.with_sender(sender)
   |  ___________________________^
36 | |         .call(contract.functions().get_sender())
37 | |         .unwrap();
   | |_________________^ expected struct `types::H160`, found ()
   |
   = note: expected type `types::H160`
              found type `()`
```

for some reason ethabi-derive generates `()` as `ContractFunction::Output` type for the `get_sender` function.
`Output` should be `H160` (Address)

here's the function in solidity: https://github.com/paritytech/sol-rs/blob/2053fe1d805dc2eb5d43abf8de81abe1a401fcb4/tests/contracts/test.sol#L2

i've confirmed it by generating docs for the derived contract.

@tomusdrw @axelchalon any ideas?

File: example/src/main.rs [hunk 2]
```diff
@@ -34,63 +33,70 @@ use solaris::wei;
...
+    assert_eq!(
+        evm.call(contract.functions().fee()).unwrap(),
+        wei::from_gwei(10)
+    );
 
     // Other address should not be allowed to change the fee
-    evm.with_sender(10.into());
-    reg.set_fee().transact(wei::from_gwei(10), &mut evm).unwrap_err();
+    evm.with_sender(10.into())
+        .transact(contract.functions().set_fee(wei::from_gwei(10)))
```
Comment (kirushik) [inline example/src/main.rs]: Minor nitpick: i would suggest putting some different number here, just to avoid a possible problem with the contract no-oping if the values match.

Also, how exactly do you check that the `set_fee` execution fails in this step?

Comment (kirushik) [reply example/src/main.rs]: (Sorry if this is not completely relevant to the more major problems of the PR)

Comment (snd) [reply example/src/main.rs]: thanks for taking a look @kirushik : )

> i would suggest putting some different number here, just to avoid a possible problem with the contract no-oping if the values match.

do you mean to use 10 as the sender and 5 as the gwei for example?

> Also, how exactly do you check that the set_fee execution fails in this step?

there's an `unwrap` below that's not changed and therefore not visible in the diff. does that answer the question?

**Comment by snd** [comment]
travis build is fixed - yay!

i'll make another pass over this soon.

feel free to start reviewing though

**Comment by snd** [comment]
ready for review. let's get this merged :)

**Comment by snd** [comment]
@tomusdrw would be fantastic to get a review sometime this week : )

File: solaris/src/evm.rs [hunk 3]
```diff
@@ -94,6 +195,11 @@ impl Evm {
         self
     }
 
+    pub fn with_tracing(&mut self, is_tracing_enabled: bool) -> &mut Self {
```
[the remark this answers is not in the document]
Comment (snd) [reply solaris/src/evm.rs]: there was a `with_tracing` param previously in the private `evm_transact` function. i wanted to keep the functionality. i agree though and will remove it

**Comment by snd** [comment]
@tomusdrw grumbles addressed.

"squash and merge" seems to be the default merge option for this repo. let me know what you prefer
